:первая сдача на проверку
PakSemen/java-filmorate pull request #1
Opened 2023-05-10 20:36 UTC by PakSemen

2023-05-11 07:05 UTC, YazykovMikhail commented
Называй комиты и ПР более предметно. 
Пиши что ты в них сделал

2023-05-11 07:23 UTC, YazykovMikhail requested changes
Сделано не плохо, молодец, но местами ты сметрел в будущее ;)

2023-05-11 07:23 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/javafilmorate/controller/FilmController.java
> +        log.info("GET {} films", filmService.getAllFilms().size());
обратив нимние что и в контроллере и в сервисе у тебя одтнаковый лог.
В контроллере он нужен, да, потому чт опришел запрос. 
Но если ничего по бизнес логике не произошло, то в точно таком же логе нет смысла. 
Логирвоание нужно что бы потом отследить ошибку видить состояние обьектов в конкретный мнмент времени. А в сервисе ничего не просизодит, такой лог в сервисе не особо нужен

Дальше, вот такой лог делать нельзя log.info("GET {} films", filmService.getAllFilms().size());
ты получется выполняешь бизнес операцию доя логирвоания, а потом еще отдельно вызывешь такой же метод.
Как стоит сделать:
```
 log.info("Request received GET  films");
 List<Film> films = filmService.getAllFilms();
 log.info("GET  films response received: {}", films);
```

Это касается всех запросов в контроллере. 
Если у запроса есть тело, то оно так же логируется в первом логе.

2023-05-11 07:23 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/javafilmorate/controller/FilmController.java
> +@Validated
У тебя и так на каждом теле запроса есть @Valid сипользуй или одно или другое

2023-05-11 07:23 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/javafilmorate/controller/FilmController.java
> +@RequiredArgsConstructor
Используй это если понимаешь как это работает, если еще не совсем, то используйю @Autowired над конструктором

2023-05-11 07:23 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/javafilmorate/model/User.java
> +    final Set<Long> friends = new HashSet<>();
а это что за поле?)))

2023-05-11 07:23 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/javafilmorate/model/Film.java
> +    final Set<Integer> likes = new HashSet<>();
А это что за поле?))

2023-05-11 07:23 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/javafilmorate/service/FilmService.java
> +    @Autowired
где то у тебя @Autowired, где то ты делаешь через ломбок. 
ЛУчше что бы было единообразно везде

2023-05-19 05:30 UTC, PakSemen commented on src/main/java/ru/yandex/practicum/javafilmorate/controller/FilmController.java
> +        log.info("GET {} films", filmService.getAllFilms().size());
если я правильно понял, то я убрал из Сервисов повторяющиеся логи, но оставил в них логи для отлова ошибок

2023-05-19 17:26 UTC, YazykovMikhail approved these changes

2023-05-24 21:45 UTC, merged