Add database
PakSemen/java-filmorate pull request #4
Opened 2023-06-24 18:09 UTC by PakSemen

2023-06-24 18:34 UTC, AlekseiZubkov reviewed
MPA  лучше вынести в отдельную таблицу

2023-07-07 12:36 UTC, YazykovMikhail requested changes

2023-07-07 12:36 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/javafilmorate/storage/impl/FilmDaoImpl.java
> +    private @NotNull Film makeFilm(@NotNull ResultSet rs, int rowNum) throws SQLException {
в makeFilm не должно быть никаких запрсов. Все даные приходят в rs
кроме жанров, жанры отдельно ставться из сервиса, потому что там запрос многие ко многим.

т,е примерно так выглядит метод(адаптируй для своих полей):
```
static Film makeFilm(ResultSet rs, int rowNum) throws SQLException {
		return new Film(
				rs.getLong("film_id"),
				rs.getString("FILMS.name"),
				rs.getString("description"),
				toLocalDate(rs.getDate("release_date")),
				rs.getLong("duration"),
				rs.getLong("rate"),
				new Mpa(rs.getLong("MPA.mpa_id"), rs.getString("MPA.name")));
	}
```

2023-07-07 12:36 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/javafilmorate/storage/impl/FilmDaoImpl.java
> +        String sqlQuery = "SELECT * FROM films";
вот тут ты делаешь джины что бы получить все данные, получается у тебя делается 1 запрос к БД и ты получаешь все данные (кроме genre потому что там многие ко многим)
`		return jdbcTemplate.query("select * from FILMS f, MPA m where f.MPA_ID = m.MPA_ID", DbFilmStorage::makeFilm);`
например вот так

2023-07-07 12:36 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/javafilmorate/storage/impl/FilmDaoImpl.java
> +        String sqlQuery = "SELECT * FROM films WHERE id = ?";
тоже самое через джоин все нужные поля. Везде где можно сделать одн запрос к БД, нужно это делать.
Потому что сам по себе запрос к БД это тяжеловестная операция, нужно их минимизировать, тем более средсвтами sql проще собрать все данные

2023-07-07 12:36 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/javafilmorate/storage/impl/FilmDaoImpl.java
> +    public void isFilmExisted(int id) {
Этот метод стоит убрать. У тебя есть метод get
коорый или возвращешь обьект или нет.
Зачем делать два запроса ради одной цели?

2023-07-07 12:36 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/javafilmorate/service/FilmService.java
>      public List<Film> getAllFilms() {
@Override
	public List<Film> getAll() {
		final List<Film> films = super.getAll();
		genreStorage.load(films); // можно сделать отдельную сторадж6 можно не делать. 
		return films;
	}
	
	вот как выглядит, и что бы в цикле не делать для каждого фильма запрос за жанрами, используется вот что:
	
	```
@Override
	public void load(List<Film> films) {
		String inSql = String.join(",", Collections.nCopies(films.size(), "?"));
		final Map<Long, Film> filmById = films.stream().collect(Collectors.toMap(Film::getId, identity()));
		final String sqlQuery = "select * from GENRES g, FILM_GENRES fg where fg.GENRE_ID = g.GENRE_ID AND fg.FILM_ID in (" + inSql + ")";
		jdbcTemplate.query(sqlQuery, (rs) -> {
			final Film film = filmById.get(rs.getLong("FILM_ID"));
			film.addGenre(makeGenre(rs, 0));
		}, films.stream().map(StorageData::getId).toArray());
	}
```

2023-07-07 12:36 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/javafilmorate/storage/impl/GenreDaoImpl.java
> +    public void isGenreExisted(int id) {
Эти методы удали из всех стораджей, Они не нужны. Для этого есть метод get

2023-07-07 12:36 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/javafilmorate/storage/impl/GenreDaoImpl.java
> +public class GenreDaoImpl implements GenreDao {
Как скзано в заднии в genre методы только get и getAll
потому что они создаются при старте приложения и не меняются

2023-07-07 12:36 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/javafilmorate/storage/impl/MpaDaoImpl.java
> +public class MpaDaoImpl implements MpaDao {
Как скзаано в заднии в Mpa методы только get и getAll
потому что они создаются при старте приложения и не меняются

2023-07-07 12:36 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/javafilmorate/service/GenreService.java
> +public class GenreService {
Как скзано в заднии в Genre методы только get и getAll
потому что они создаются при старте приложения и не меняются

2023-07-07 12:36 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/javafilmorate/storage/GenreDao.java
> +public interface GenreDao {
Как скзано в заднии в Genre методы только get и getAll
потому что они создаются при старте приложения и не меняются

2023-07-07 12:36 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/javafilmorate/service/GenreService.java
> +    public Genre getGenreById(Integer id) {
А почему методы дублируются?

2023-07-08 21:14 UTC, YazykovMikhail requested changes

2023-07-08 21:14 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/javafilmorate/storage/impl/GenreDaoImpl.java
> +    public void updateFilmGenre(@NotNull Film film) {
Как говорил в предыдущем ревью, этого метода тут не должно быть, только
get и getAll
ну и load

2023-07-08 21:14 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/javafilmorate/storage/impl/GenreDaoImpl.java
> +    public void createFilmGenre(Film film) {
Как говорил в предыдущем ревью, этого метода тут не должно быть, только
get и getAll
ну и load

обновляй эту таблицу когда вставялкешь фильм, в том же методе. в сервисе скину пример.

2023-07-08 21:14 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/javafilmorate/service/FilmService.java
> +        genreStorage.createFilmGenre(film);
Т.е вместо этого вот как будет выглядить метод сохрания фильма:

```
@Override
	public void save(Film film) {
		String sqlQuery = "insert into FILMS (NAME, DESCRIPTION, RELEASE_DATE, DURATION, RATE, MPA_ID) values (?, ?, ?, ?, ?, ?)";

		KeyHolder keyHolder = new GeneratedKeyHolder();
		jdbcTemplate.update(connection -> {
			PreparedStatement stmt = connection.prepareStatement(sqlQuery, new String[]{"FILM_ID"});
			stmt.setString(1, film.getName());
			stmt.setString(2, film.getDescription());
			stmt.setDate(3, Date.valueOf(film.getReleaseDate()));
			stmt.setLong(4, film.getDuration());
			stmt.setLong(5, film.getRate());
			stmt.setLong(6, film.getMpa().getId());
			return stmt;
		}, keyHolder);
		film.setId(keyHolder.getKey().longValue());

		saveGenres(film);
	}

	private void saveGenres(Film film) {
		final Long filmId = film.getId();
		jdbcTemplate.update("delete from FILM_GENRES where FILM_ID = ?", filmId);
		final Set<Genre> genres = film.getGenres();
		if (genres == null || genres.isEmpty()) {
			return;
		}
		final ArrayList<Genre> genreList = new ArrayList<>(genres);
		jdbcTemplate.batchUpdate(
				"insert into FILM_GENRES (FILM_ID, GENRE_ID) values (?, ?)",
				new BatchPreparedStatementSetter() {
					public void setValues(PreparedStatement ps, int i) throws SQLException {
						ps.setLong(1, filmId);
						ps.setLong(2, genreList.get(i).getId());
					}

					public int getBatchSize() {
						return genreList.size();
					}
				});
	}
```

2023-07-08 21:14 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/javafilmorate/service/FilmService.java
> +        genreStorage.updateFilmGenre(film);
То же самое с обновлением:

```
@Override
	public void update(Film film) {
		String sqlQuery = "update FILMS SET NAME = ?, DESCRIPTION = ?, RELEASE_DATE = ?, DURATION = ?, RATE = ?, MPA_ID = ? " + " WHERE FILM_ID = ?";
		jdbcTemplate.update(sqlQuery, film.getName(), film.getDescription(), film.getReleaseDate(), film.getDuration(), film.getRate(), film.getMpa().getId(), film.getId());
		saveGenres(film);
	}
```

2023-07-08 21:14 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/javafilmorate/service/FilmService.java
> +        filmStorage.getFilmById(film.getId());
можно не проверять что фильм есть, как говорил надо старатсья избегать лишних запросов в БД.
Теперь же у нас БД, и если при обновлении он не найдет нужный обьект для обнволения , база и так вернет ошибку. Так что в этом запросе нет особого смысла

2023-07-08 21:14 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/javafilmorate/service/FilmService.java
> +        daoStorage.getMpaById(film.getMpa().getId());
Тоже проверять особого смысла нет

2023-07-08 21:14 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/javafilmorate/service/FilmService.java
> +    private final MpaDao daoStorage;
private final MpaDao mpaStorage;

2023-07-08 21:14 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/javafilmorate/service/FilmService.java
> +        filmStorage.getFilmById(filmId);
у тебя задублировались две строчки
     filmStorage.getFilmById(filmId);
        userStorage.getUserById(userId);

2023-07-08 21:14 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/javafilmorate/service/UserService.java
> +        //userStorage.isUserExisted(id);
удаляй сразу

2023-07-08 21:14 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/javafilmorate/service/FilmService.java
> +        log.info("GET {} films", filmStorage.getAllFilms().size());
Так не делай. Ты достал всю базу лишь для того что бы записать лоГ. а потом еще раз.
Тем более действие еще  не было совершено, а ты уже запсиал в лог

```
public List<Film> getAllFilms() {
        List<Film> films = filmStorage.getAllFilms();
        genreStorage.loadGenres(films);
        log.info("GET {} films", filmStorage.getAllFilms().size());
        return films;
    }
```

Поправь такое везде

2024-09-10 14:58 UTC, merged